version: "3.9"  # optional since v1.27.0
services:

  rshiny:
    image: ff14-stats
    restart: always
    depends_on:
      - db
    ports:
      - "8888:8888"
    links:
      - db
    environment:
      - FF14_PASSWORD=${FF14_PASSWORD}
      - FF14_USER=${FF14_USER}



  db:
    image: mysql:8
    command: --sql-mode=""
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var
    environment:
      - MYSQL_DATABASE=myDatabase
      - MYSQL_ROOT_PASSWORD=${FF14_PASSWORD}


volumes:
  db_data: 
